### ISSUE TITLE
Registration, Login and protect private area

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#1]
We need simple registration form. Mandatory fields should be email and password and the rest will be considered later.

After registration is complete an users should be able to login via login form.

We will need the rest of the pages that are not register and login to be protected and not reachable until a visitor in not logged in.

**Comment by ceckoslab** [comment]
I will most likely use Sonata User Bundle. Reference here: https://sonata-project.org/bundles/user/4-x/doc/reference/installation.html

**Comment by ceckoslab** [comment]
Here is how it will work:

We will have 2 user groups:
 - **Admin**
 - **User**

**Admin**:
- We will have a master admin that will be created during project installation
- The master admin will be the only person able to create User accounts
- Will be able to login/restore password via forgot password page/change his password after logged in.

**User**:
- Will be able to login/restore password via forgot password page/change his password after logged in.

**Session timeout**:
 - A session will be valid for 30 minutes.
 - If session expires because of inactivity then a user or admin will be redirected to a login screen with notification message.

**Comment by korzol** [comment]
Here are few first preview new user registration screenshots
Registration form  
![basicrum registration_form](https://user-images.githubusercontent.com/48809063/75223378-fa17a100-57ae-11ea-92bf-834af08101e7.png)

Frontend validation
![basicrum frontend_validation](https://user-images.githubusercontent.com/48809063/75223414-14ea1580-57af-11ea-99aa-7c42acd93309.png)

Serverside validation
![basicrum server_side_validation](https://user-images.githubusercontent.com/48809063/75223421-17e50600-57af-11ea-9dbe-d2bebb4d0f90.png)

**Comment by ceckoslab** [comment]
Great @korzol 

Would we have a list/grid of all users where the master admin could look at all the users and perhaps perform actions like disabling users?

Have nice day!

**Comment by ceckoslab** [comment]
Implemented by @korzol 

Closing!
