### ISSUE TITLE
Add CONTRIB file and instructions

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#107]
Add:
- PHP CS fixer instruction: ```vendor/bin/php-cs-fixer fix --config=./.php_cs```

**Comment by korzol** [comment]
Hello @ceckoslab 
Is there anything here I can help with ?

Please clarify

**Comment by ceckoslab** [comment]
Hello @korzol 

I am going to add notes in a CONTRIB files. 

So far I would like to document instructions:
 * PHP CS fixer instruction
 * Unit tests
 * Creation of Pull Requests

Do you have any other ideas?

**Comment by korzol** [comment]
Hello @ceckoslab 
Looks like you already covered all major things
