### ISSUE TITLE
GitHub sponsors

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#108]
Checkout this account and see what ideas we can use for our sponsor page: https://github.com/sponsors/calebporzio

**Comment by korzol** [comment]
Hello @ceckoslab 
I checked the page you have provided. I am not sure if we can create something similar to their sponsor packages. But if we can it might be of help. Of course adopted to our current situation. 
Just for example:
1. $15 - just to support development. With possible access to some other paid options with some predefined discount.
2. $25 - individual installation support, once we reach release stage
3. $50 - a promise for a good discount on individual feature development
4. $75 - all together

A promise is a good thing we can give back to sponsors at the moment.

Should we also consider crowdfunding websites?

**Comment by ceckoslab** [comment]
It's worthy to check crowdfunding websites.

I already checked this one opencollective.com but it requries 100 GitHub stars in order to complete the registration process.

**Comment by ceckoslab** [comment]
As we discussed today with @eliskovets we probably will add $5 tier.
