### ISSUE TITLE
Check if PHP CS fixer works

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#110]
Hello @korzol 

Could you check if the instructions we have wrote about the GIT hook and PHP CS fixer work correctly?

I tried to run this part but I got an error: ```vendor/bin/php-cs-fixer fix --config-file=./.php_cs```

This is the error: ```The "--config-file" option does not exist.```

I tried with ```vendor/bin/php-cs-fixer fix --config=./.php_cs``` and it worked!

**Comment by korzol** [comment]
Hello @ceckoslab 
Yeah, you are right. Already fixed README.txt and created pull request. 
Kindly review
