### ISSUE TITLE
Problem loading the demo data

### ISSUE THREAD

**Issue by NikolovI** [basicrum/backoffice#119]
Hello,

I'm experiencing some issue with the diagrams data after setting up the project using the latest makefile. I was able to build and run the project with and without the demo data and experienced the same issue. The problem is with the diagrams' loading. All XHR requests for diagram generations are returning 500 Internal Server Error with the following:

![Screenshot_2020-05-07 Notice Undefined index APP_ENV (500 Internal Server Error)](https://user-images.githubusercontent.com/63069313/81333390-3a4ba780-90ad-11ea-93a2-ec881924aa4e.png)

The .env file was empty and ignored and I was unable to get any data running until I added the followng:
`
###> symfony/framework-bundle ###
APP_ENV=dev
APP_SECRET=a61405770c0c9097569cd6c494a60a7b
#TRUSTED_PROXIES=127.0.0.1,127.0.0.2
#TRUSTED_HOSTS=localhost,example.com
###< symfony/framework-bundle ###
`

I'm not sure if this was a problem with the setup in Windows or If I missed something so any tips will be greatly appreciated :)

Thanks!

**Comment by ceckoslab** [comment]
Hello @NikolovI 

Could you delete `.env` from the project holder. You may need to do this from inside the symfony container.

After that try to run `make rebuild`.

I believe that this should fix the problem.

@eliskovets do you think that we should recreate the the `.env` every time when we run rebuild?

**Comment by eliskovets** [comment]
Hi @ceckoslab , 
The idea behind keeping .env file and create it only if it doesn't exist was that if user already configured something specific, then it's not going to disappear, but as we actually reset everything else(even DB) on `make rebuild`, probably it make sense to replace `.env` file by a default one as well. 
I will prepare a PR with these changes.
