### ISSUE TITLE
Installation under windows

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#121]
Hello @NikolovI 

We would like to update our docs in order to make them suitable for folks who develop on Windows.

Could you share couple screenshots and steps you've went through on your Windows system?

Thanks in advance!

**Comment by NikolovI** [comment]
Hello,

I'm adding instructions draft, please let me know if it will do the job:

1. Install Cygwin

2. When selecting Cygwin packages make sure you have selected **"make"** and **"git"** packages (latest version should be fine)
![cygwin-make](https://user-images.githubusercontent.com/63069313/82035104-c3636f80-96a7-11ea-8520-7b08f8c1eace.jpg)
![cygwin-git](https://user-images.githubusercontent.com/63069313/82035119-c8c0ba00-96a7-11ea-8bc4-963faa3c4ce3.jpg)

3. Install Docker Desktop for Windows and make sure it is running. You should be able to see the empty docker dashboard
![docker-empty](https://user-images.githubusercontent.com/63069313/82035207-e42bc500-96a7-11ea-8e00-5378a8f35f60.jpg)

4. Open Cygwin terminal and navigate to your project folder

5. Run the **"make init"** command, follow the instructions for user creation and, if there are no errors in the terminal, you should be able to see the docker container running.
![docker-running](https://user-images.githubusercontent.com/63069313/82035334-0c1b2880-96a8-11ea-9dc7-a66d7018e052.jpg)

6. Open http://localhost:8086/ or click on the "Open in browser" button in the basicrum_bo_nginx container to view the back-office
![docker-browse](https://user-images.githubusercontent.com/63069313/82035429-2bb25100-96a8-11ea-8680-12e6b4982965.jpg)

7. If you like to have the demo data installed, in the Cygwin terminal, run the **"make demo"** command

8. After the initial install process is completed you can use the Cygwin terminal **"make up"** command to start your docker instance again when needed (e.g. after restart)

**Comment by ceckoslab** [comment]
Thank you @NikolovI 

We will wrap your notes in a how to article soon.

Small questions about:

1 ) Install Cygwin

Do you download it from here: https://www.cygwin.com/

2 ) When selecting Cygwin packages make sure you have selected "make" and "git" packages (latest version should be fine).

Did you get a popup about the packages option when you started an installation process? If possible could you add a screenshot that shows a bit more about the context/where are you seeing the things on the UI?

**Comment by NikolovI** [comment]
> 
> 
> Thank you @NikolovI
> 
> We will wrap your notes in a how to article soon.
> 
> Small questions about:
> 
> 1 ) Install Cygwin
> 
> Do you download it from here: https://www.cygwin.com/

Yes, this is the required software

> 
> 2 ) When selecting Cygwin packages make sure you have selected "make" and "git" packages (latest version should be fine).
> 
> Did you get a popup about the packages option when you started an installation process? If possible could you add a screenshot that shows a bit more about the context/where are you seeing the things on the UI?

This is part of the setup process. Basically you're installing packages that you need, because Cygwin contains tons of stuff and you can't install everything. On my screenshots above you see only the part of the setup wizard with the needed packages. The entire, unfiltered screen looks like this:

![capture_001_20052020_082833](https://user-images.githubusercontent.com/63069313/82408272-f1fc9400-9a73-11ea-817b-7224ca0be15b.jpg)

Main things are the Current/New columns of the table. Current will show the installed version (if installed). New will allow you to install/update to specific version. If the drop-down menu has Skip selected - the package will not be installed.

Hope this makes more sense :)

**Comment by ceckoslab** [comment]
Thanks @NikolovI 

I ported your notes here: https://github.com/basicrum/backoffice/blob/master/doc/installation/WINDOWS.md
