### ISSUE TITLE
Cleanup RAW beacons after Bundle command

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#138]
We forgot to clean the raw beacons after bundling process. 

Let's add some extra code that deletes the bundled raw beacons.

**Comment by korzol** [comment]
Hello @ceckoslab 
I just made PR with code to remove raw beacons. However there still exists a problem:
When the following command is issued it process all bundle files and store all available data into db. Again and again and again
```
bin/console basicrum:beacon:import-bundle
```

I think we should implement some mechanism to prevent inserting already stored data into DB. 
I think this could be:
1. archive bundle beacons 
2. remove them
3. use bundle file name as beacon id in DB and do not process if bundle file name already exists in DB
What do you think?

**Comment by ceckoslab** [comment]
Hello @korzol 

I merged the related changes with this ticket. Could you work on this ticket and check if the outstanding problems are resolved: https://github.com/basicrum/backoffice/issues/142
