### ISSUE TITLE
Improve admins session control

### ISSUE THREAD

**Issue by korzol** [basicrum/backoffice#155]
Hello @ceckoslab 
In one of our discussions you mentioned better session expiration handling in frontend.
What we have currently we have implemented in frontend is very simple and probably annoying. 
Obviously there is place for improvement from technical point of view. 
Lets discuss how we can improve it. For start here are some entry details:
Currently our symfony installation use PHP session. 

Here is a screenshot for default PHP session related settings
![image](https://user-images.githubusercontent.com/48809063/87680814-8f2f2c80-c786-11ea-8284-c1684666de0f.png)

So as seen in the picture above PHP uses session cookies and their lifetime is set to 0. Which means session will lasts as long as browser remains open. 

Probably there no need to change session settings and only implement session control in frontend which would work kind like this:

1. Send request to server
2. Code in backend check if session still alive
3. Send a signal to frontend, like following :
3.1 Session is alive
3.2. Session is died
4. Frontend acting accordingly 
4.1. Awaiting for next request 
4.2. Redirect to /logout

We can make it so that session will be checked on every XHR request but besides this do we need some timeout to be implemented?

**Comment by ceckoslab** [comment]
Hello @korzol 

We can check for inactivity period of for example 30 minutes. If user's session is inactive for more than 30 minutes then a user must be logged out and redirected to the login page. Also the user must see a notification that the session has expired.

We also can do periodical checks with JavaScript ... let's say every 20 seconds if a session is still active and if a session is not active then we again redirect to login page and display an notification that the session has expired.

Do you think that it will be possible in Symfony? I don't know how this can be done in Symfony? Is there a way to check for authentication and return JSON?

**Comment by korzol** [comment]
Hello @ceckoslab 
Yes, of course it can be done in Symfony. 


> We can check for inactivity period of for example 30 minutes.

We can run this check in frontend


> Also the user must see a notification that the session has expired.

I think it would be even more user friendly to present to user a warning lets say 5 minutes before expiration with a countdown timer


> We also can do periodical checks with JavaScript ... let's say every 20 seconds if a session is still active and if a session is not active then we again redirect to login page and display an notification that the session has expired.

Currently we are using standard PHP session within Symfony hence we can check if session still alive with standard php function - session_status() which return one of three values: 
> PHP_SESSION_DISABLED if sessions are disabled.
> PHP_SESSION_NONE if sessions are enabled, but none exists.
> PHP_SESSION_ACTIVE if sessions are enabled, and one exists.

Additionally we can use Symfony's security bundle feature to check if user still logged in. 
Once user logged in $this->getUser() within controller and $this->security->getUser() within service represents Users entity initiated for currently logged in user. So we can access current user data like this: $this->getUser()->getId(); (all other getters from Users entity available as well) if it still exists - okay, if not - redirect to login

We can check both PHP session and user data for additional security and return user array encoded to JSON to frontend - if session is active and error if session is died.

**Comment by ceckoslab** [comment]
Closing - we move to Grafana
