### ISSUE TITLE
User Agents - segmetation per web view and browser family

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#30]
I found some interesting cases that really skew the filter results and I need to give more focus to this problem at some moment.

So far I can relate this to Chromium based browsers and browsers embeded in a web view. We have Facebook web views and also Yandex Browser:

This User Agent is from a link that was opened from Facebook mobile app:
```
Mozilla/5.0 (Linux; Android 7.0; RNE-L21 Build/HUAWEIRNE-L21; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/72.0.3626.105 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/211.0.0.43.112;]
```

Currently I mark this a Facebook browser but it is actually a web view. I need to figure out what is the best way to mark this in the database and later to provide proper UI where users will understand that this is a web view.

There is another case with Yandex Browser which also suppose to be build on top of Chromium but now I mark it in the DB as Yandex Browser:
```
Mozilla/5.0 (Linux; Android 8.0.0; ATU-L31) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 YaBrowser/19.3.4.339.00 Mobile Safari/537.36
```

I will need some planning and will come back later to this issue.

**Comment by ceckoslab** [comment]
Also it will be great if we normalize the OS version.

Sometimes I record **8.0.0** and sometimes **8** I think that the best will be just to keep the major version number. So in the example above the I will keep just **8**.

**Comment by korzol** [comment]
Hello @ceckoslab 
I found one interesting solution for problem you described here. 
Check it out:
Code and description: https://github.com/WhichBrowser/Parser-PHP
Demo: https://whichbrowser.net/tryout/

**Comment by ceckoslab** [comment]
Hello @korzol 

Thanks for your research. As a matter of fact we already use WhichBrowser in Basic RUM. 

The problem I described here was that we call a browser "Facebook Browser" but in reality it's a Chromium that works as a web view.
