### ISSUE TITLE
Add new data/metrics

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#46]
Hello @korzol 

This will be our next task. Read the following and feel free to drop comments where things are unclear.

Before start look at this diagram (Navigation Timings diagram):
<img src="https://raw.githubusercontent.com/micmro/resourceTable/gh-pages/readme-assets/navigation-timing-overview.png" alt="Diagram of the Navigation Timing API as seen on W3C site" style="max-width:100%;">

We attach all this data to our page view beacons.

We would like to add more data to Basic RUM db and add this data to our diagrams:

 - Total Backend time (from Request Start to Response Start) - Reference Navigation Timings diagram 
 - Download time (from Response Start to Response End) - Reference Navigation Timings diagram
 - Total JS Uncompressed size
 - Total JS Compressed Size
 - Total CSS Uncompressed size
 - Total CSS Compressed Size
 - Total Img Size
 - Number of JS files
 - Number of CSS files
 - Number of Img files
 - http.initiator - we need to add RT plugin and read a bit more from here: https://developer.akamai.com/tools/boomerang/docs/BOOMR.plugins.RT.html
 - rt.quit - part of RT plugin ... we need to research this.

We would like to add this data to **navigation_timings** table. Also all for each new data field we will need to add filters and metric classes.

**Comment by ceckoslab** [comment]
Hello @korzol 

As we discussed this task to big for the beginning so we will start with small chunk of it.

Let's first start with the first item of our list: "Total Backend time (from Request Start to Response Start) - Reference Navigation Timings diagram"

For this sub-task we will have:

- New DB Field: `navigation_timings`.`ttfb`
- We will have to add new class in src/BasicRum/TechnicalMetrics/
- We will need to register this class in src/BasicRum/TechnicalMetrics/Collaborator.php

Also in order to recreated the complete process from sending a beacon to importing it in the DB and visualizing it we will need to send some beacons to our Basic RUM local installation.

Could you please create a local static page where we will run Boomerang JS (https://github.com/akamai/boomerang). From this page we will send beacons to Basic RUM. 

Check this page: https://github.com/akamai/boomerang#usage where we have an example how to configure Boomerang to send a beacon to a remote location.

**Comment by korzol** [comment]
I am on it. 
Going to setup local test environment

**Comment by korzol** [comment]
> Total JS Uncompressed size
> Total JS Compressed Size

Do you mean encodedBodySize and decodedBodySize from restiming? 
Please clarify

**Comment by ceckoslab** [comment]
Hello @korzol 
Good catch about JS size.

Yes it should be taken from restiming. I have some doubts that we probably will have to have these sizes from 1st party and 3rd party scripts. This should not be a big deal :) 

Could you push the current changes you have in the beginning of next week so I can see how things are going the current code structure because as you see it's a bit messy right now ;)

Have a nice weekend.

**Comment by korzol** [comment]
Probably I miss something but I can not understand the logic behind the way diagram generator work. 
For example see attached screenshot. This is Time to first byte diagram. Although as you can see it has single value - 2 Which (in my opinion) is count and not real values from navigation_timings table.
![basicrum lc_diagram_generator_](https://user-images.githubusercontent.com/48809063/76640588-deefb400-6558-11ea-9044-7b6a4ad90747.png)

Here is another screenshot. Just for for references. It is navigation_timings table

![phpmyadmin lc_sql php_db=basicrum table=navigation_timings pos=0](https://user-images.githubusercontent.com/48809063/76641671-9df89f00-655a-11ea-87a2-2ab9edf8ac7f.png)

**Comment by ceckoslab** [comment]
@korzol could you send more beacons for example 5 more beacons. Then run the symfony command: **basicrum:cache:clean** and reload the diagram again.

Post the results here so we can compare.

**Comment by korzol** [comment]
@ceckoslab here you go

![basicrum lc_diagram_generator_2](https://user-images.githubusercontent.com/48809063/76643062-0c3e6100-655d-11ea-9228-5ab769b2720d.png)

![phpmyadmin lc_sql php_db=basicrum table=navigation_timings pos=0 (1)](https://user-images.githubusercontent.com/48809063/76643080-13fe0580-655d-11ea-930e-79802c83f033.png)

**Comment by ceckoslab** [comment]
@korzol I think that this is related to a parameter called **bucket**.

Could you change some of the values in the DB to 1000, 1300 and 1500?

Probably it's showing you 14 because all your loads are below 200 miliseconds.

We also have a hidden input that controls the bucket size. You can find it on the page:
<input type="hidden" name="global[data_flavor][histogram][bucket]" value="200">
