### ISSUE TITLE
CRUD - JSON Diagram config

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#56]
Hello @korzol 

After we finish with https://github.com/basicrum/backoffice/issues/53 and https://github.com/basicrum/backoffice/issues/46 we will continue with a CRUD for creating user defined JSON configs for diagrams. This will allow us to test quickly when we add new metrics or we would like to create a new diagram. We would not seek perfection in this ticket!

Before we write a single line of code please read again "5. Diagram configuration format and Data Flavors" from https://calendar.perfplanet.com/2019/lessons-learned-from-developing-my-real-user-monitoring-system-basic-rum/ and watch https://www.youtube.com/watch?v=9uaHRWj04D4

We already have examples for JSON configs for diagrams in **backoffice/templates/dashboard.html.twig** 

On the view action we will read the JSON config and we will render a diagram in the same fashion we do in **backoffice/templates/dashboard.html.twig**

Also in this ticket I would like that we research different JS libraries for autocomplete and JSON schema validation.

**Comment by ceckoslab** [comment]
Hello @korzol 

In the navigation we will add a new item called "Widgets" and when a user clicks on it will see similar CRUD we have for "Manage Users" CRUD. 

In the CRUD we will have:

- name
- user (username of a widget creator)
- created at
- updated at

I also suggest that we implement the add/edit part on 2 iterations:

1. Implement very basic crud that just have very basic text area where an user can add JSON diagram config.
2. After we finish with step 1 we will test a bit and then we will JSON schema autocomplete/validator that will show validation errors in the text area while a user is creating a JSON diagram config.

**Comment by korzol** [comment]
Hello @ceckoslab 
Cool. Sounds good. 
Going to work on this task. Seems now I have everything I need

**Comment by ceckoslab** [comment]
Hello @korzol I upgraded to Symfony 5 https://github.com/basicrum/backoffice/issues/51 

Please sync your branch with master in order to avoid any issues in the future.
