### ISSUE TITLE
JSON Schema for JSON diagram config

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#81]
Hello @korzol 

After we finish with https://github.com/basicrum/backoffice/issues/56 we will implement JSON schema validation and autocomplete.

I did some research and I found this project that looks really promising: https://github.com/josdejong/jsoneditor

We will start with static hardcoded JSON schema but in another ticket we will think how we can make the schema dynamic based on what metrics we have.

**Comment by korzol** [comment]
Hello @ceckoslab 
So I have implemented aforementioned JSON editor but there is a problem with it.
When I use enum in schema it should generate selectbox for that entry. Although it works for static - hardcoded entries, it doesn't for entries lets say in definitions. Once I met this for my schema implementation, I decided to test the one provided as example on [json-schema.org - Structuring a complex schema](https://json-schema.org/understanding-json-schema/structuring.html)

Here is it:
```js
const schema2 = {
          "$schema": "http://json-schema.org/draft-07/schema#",

          "definitions": {
            "address": {
              "type": "object",
              "properties": {
                "street_address": { "type": "string" },
                "city":           { "enum": ["Washington", "New-York"] },
                "state":          { "type": "string" }
              },
              "required": ["street_address", "city", "state"]
            }
          },

          "type": "object",

          "properties": {
            "billing_address": { "$ref": "#/definitions/address" },
            "shipping_address": { "$ref": "#/definitions/address" }
          }
        };

        const json2 = {
            "shipping_address": {
                "street_address": "1600 Pennsylvania Avenue NW",
                "city": null,
                "state": "DC"
              },
            "billing_address": {
                "street_address": "1st Street SE",
                "city": null,
                "state": "DC"
            }
        };

const options = {
        schema: schema2,
        mode: 'tree',
        modes: ['code', 'text', 'tree', 'preview'],
    };

const container = document.getElementById('jsoneditor');
const editor = new JSONEditor(container, options, json2);
```

Here is the result:
![jsoneditor-bug](https://user-images.githubusercontent.com/48809063/78793548-3992f900-79bb-11ea-8723-93e8e489fd22.png)

As seen from provided screenshot the editor proceed schema although fails to generate selectbox 

There is a bug filled out - https://github.com/josdejong/jsoneditor/issues/473

**Comment by korzol** [comment]
Here is a result for our real schema & json
![jsoneditor-bug2](https://user-images.githubusercontent.com/48809063/78794478-7b706f00-79bc-11ea-817f-de3e86e7fed5.png)

segments.1.presentation.type is enum and should be a select box (html tag)

**Comment by korzol** [comment]
![jsoneditor-bug3](https://user-images.githubusercontent.com/48809063/78797719-c12f3680-79c0-11ea-974f-d7c8294fd11c.png)
![jsoneditor-bug4](https://user-images.githubusercontent.com/48809063/78797870-f6d41f80-79c0-11ea-8139-5de77da57def.png)

**Comment by ceckoslab** [comment]
Hello @korzol 

It looks good and I think that we can continue even with the glitch you've described about the Select box.

I played a bit the JSON editor. I see some missing control icons, could we add them?

Also could we make the popup higher and wider in order to have more visible space where we can write?

**Comment by korzol** [comment]
Okay, thanks for update. 

> Also could we make the popup higher and wider in order to have more visible space where we can write?  

Yes, of course, I will do it in the morning.

Although what control icons you mean?
