### ISSUE TITLE
Travis CI integration on new PR

### ISSUE THREAD

**Issue by ceckoslab** [basicrum/backoffice#82]
We need to have a Travis CI that spins a test environment on new PR.

In the test environment we will:
1. Run all tests 
2. Import beacons
3. Run all the essential cron jobs

If all tests pass then we will be able to merge a PR after review.

**Comment by korzol** [comment]
Hello @ceckoslab 
> 3. Run all the essential cron jobs

What exactly do you mean? Please clarify

**Comment by ceckoslab** [comment]
Hello @korzol 

By essential tasks I mean all console commands that are prefixed with **basicrum**

Here are all essential tasks that we have till this moment:

-   basicrum:beacon:archive-bundle             
-   basicrum:beacon:bundle-raw                 
-   basicrum:beacon:bundle-remote              
-   basicrum:beacon:import-bundle              
-   basicrum:beacon:init-folders               
-   basicrum:cache:clean                       
-   basicrum:last-blocking-resource:calculate  
-   basicrum:superadmin:create
-   basicrum:visit:generate  

Please do not run basicrum:beacon:bundle-remote because it still unfinished.

Run them 5 times in this order: 

1.   basicrum:beacon:archive-bundle             
2.   basicrum:beacon:bundle-raw                 
3.   basicrum:beacon:import-bundle              
4.   basicrum:beacon:init-folders               
5.   basicrum:cache:clean                       
6.   basicrum:last-blocking-resource:calculate  
7.   basicrum:superadmin:create
8.   basicrum:visit:generate

What do I mean by 5 times: 1,2,3,4,5,6,7,8 **|** 1,2,3,4,5,6,7,8 **|** 1,2,3,4,5,6,7,8...

**Comment by ceckoslab** [comment]
@korzol you do not have to really run them in a cron task but just in 5 cycles in Travis CI.

**Comment by ceckoslab** [comment]
Hello @korzol great job!

I have just on wish that we can work on **during next week**.

When I tested Travis CI it failed for the first build. The problem was familiar to me because I had to deal with it when I was building some Docker containers previously for Basic RUM.

Probably we will need to have this snippet for the migrations step:

```
while [ -z "$($PWD/bin/console doctrine:migrations:migrate --no-interaction)" ]; do
 echo 'Waiting for MySql to start ...' && sleep 2
done
```
Also could you add maximum number of retries? I think that 10 retries should be fine.

This is what happened in Travis:

```
docker exec basicrum_bo_php bin/console doctrine:migrations:migrate
In AbstractMySQLDriver.php line 93:
                                                                              
  An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused  
                                                                              
In PDOConnection.php line 31:
                                             
  SQLSTATE[HY000] [2002] Connection refused  
```

The problems come of the fact that sometimes the MySql is not fully operational. E.g. the MySql container is running but the MySql process is still doing some initialization work. As a solution we should retry until the MySql container is completely initialized.
