### ISSUE TITLE
Issues with project setup on Docker Desktop for Windows

### ISSUE THREAD

**Issue by NikolovI** [basicrum/backoffice#85]
Hello,

I'm experiencing some issues with the project setup. Trying to get things running on Docker Desktop for Windows 10 following the instructions provided in the readme document. Since I'm not really familiar with the environment some issues and questions may look silly to you but please bear with me :)

First issue appeared when trying to execute the command for Symfony Flex update:
`docker exec basicrum_bo_php composer update symfony/flex --no-plugins --no-scripts`

The execution stopped with "Fatal error: Allowed memory size of X bytes exhausted (tried to allocate Y bytes)". I managed to resolve this by changing the _memory_limit_ value, but I was wondering if this should be done in the environment settings in order to avoid anyone else having the same issue?

Second issue is related to the super admin user creation. When I executed the provided command in the power shell got an error "SQLSTATE[42S02]: Base table or view not found" for the _basicrum_demo.user_ table. I'm adding screen from the shell feedback:

![capture_001_02042020_203224](https://user-images.githubusercontent.com/63069313/78354079-dae11000-75b3-11ea-8d20-33c2dd44fb20.jpg)

The back office is starting up fine, I was able to reach the login page but after I tried login with random credentials got the same error:

![capture_002_02042020_203349](https://user-images.githubusercontent.com/63069313/78354304-47f4a580-75b4-11ea-9244-359a357b5b62.jpg)

I'm not quite sure if the example database was corrupted or unzipping it on my windows machine broke it somehow but I'm stuck. 
Any provided help with the setup will be greatly appreciated :)

Thank you!

**Comment by korzol** [comment]
Hello @NikolovI 
Thanks for feedback
The project is under active development and some parts of it can be changed anytime.

>First issue appeared when trying to execute the command for Symfony Flex update:
docker exec basicrum_bo_php composer update symfony/flex --no-plugins --no-scripts

I am not sure this command is really required. In my opinion it should be replaced with:
```
docker exec basicrum_bo_php composer install
```
It should run without problem. 

As of :
>Second issue is related to the super admin user creation. When I executed the provided command in the power shell got an error "SQLSTATE[42S02]: Base table or view not found" for the basicrum_demo.user table. 

Kindly check if you have the following file:
src/Migrations/Version20200312181539.php
and if so, check if it contains the following line in it:
```php
$this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, roles LONGTEXT NOT NULL COLLATE utf8mb4_bin, password VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, fname VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, lname VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, restore_password VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
```

Let me know

**Comment by NikolovI** [comment]
Hello,

Thanks for your quick reply! Regarding your last comment:

> Kindly check if you have the following file:
> src/Migrations/Version20200312181539.php
> and if so, check if it contains the following line in it:
> 
> ```
> $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL COLLATE utf8mb4_unicode_ci, roles LONGTEXT NOT NULL COLLATE utf8mb4_bin, password VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, fname VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, lname VARCHAR(255) NOT NULL COLLATE utf8mb4_unicode_ci, restore_password VARCHAR(255) DEFAULT \'NULL\' COLLATE utf8mb4_unicode_ci, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB COMMENT = \'\' ');
> ```
> 
> Let me know

The file exist in the provided location, it is not modified and up to date with the latest version in the master branch. I was able to find the line of code you've provided above...

Thanks

**Comment by ceckoslab** [comment]
Hello @korzol  and @NikolovI 

I think that @NikolovI  is experiencing this problem because he followed our instructions where he imported an SQL file as we wrote:
```
curl https://www.revampix.com/basic_rum/test_data/may-july-2019.sql.gz -o may-july-2019.sql.gz
gunzip -k may-july-2019.sql.gz
cat may-july-2019.sql | docker exec -i basicrum_bo_mysql sh -c 'mysql -uroot -prootsecret'
```
This dump is outdated and the migrations won't run smoothly because most of the tables are already created. E.g. navigation_timings table exists in the dump and migration **Version20200312181539.php** will fail because we have:
```
$this->addSql('CREATE TABLE navigation_timings (page_view_id INT UNSIGNED AUTO_INCREMENT NOT NULL.............')
```

1. I suggest that for now we provide him a new up to date dump and update our documentation with to point to the up to date dump.

2. We file a ticket to ourselves where we describe the problem and find a way for better installation/migration process.

**Comment by korzol** [comment]
Hello @NikolovI and @ceckoslab 

Here is fixed dump 
[basicrum_demo.sql.gz](https://github.com/basicrum/backoffice/files/4439306/basicrum_demo.sql.gz)

It contains empty beacons table because it is the biggest one and same time contain no useful data. So dump size is drastically smaller now.

@NikolovI kindly give it a try and let me know
Thank you

**Comment by NikolovI** [comment]
Hello,

Sorry for the delay! Tried with the new db dump and I was able to create the super user successfully! Thanks for the help @korzol and @ceckoslab !

**Comment by korzol** [comment]
Hello @NikolovI ,
Glad it works for you.

Thank you for update!

**Comment by ceckoslab** [comment]
Hello @NikolovI I am closing this ticket and just for FYI we are completing a ticket where a PHPMYADMIN can be run locally in order to make our lives easier ;)
