### ISSUE TITLE
Need a way to provide actual MySQL dump

### ISSUE THREAD

**Issue by korzol** [basicrum/backoffice#92]
We have met a situation where actual MySQL dump and the dump with data are two different dumps. And installation description provided in README.txt doesn't reflect the problem. 
So need to find a better way to provide actual DB dump and update README accordingly

**Comment by ceckoslab** [comment]
Hello @korzol 

The best solution will be a solution where we do not need to care about the DB schema.

One way is to have:
1. Archive of raw beacons that we extract in var/beacons/raw.
2. Then we run all needed tasks to import the beacons. 
3. We cleanup after ourselves and delete the processed beacons.

This will ensure that we always import beacons on in new schema.

**Comment by korzol** [comment]
> Archive of raw beacons that we extract in var/beacons/raw.

Do we have anywhere those raw beacons? Or still need to gather them first?

**Comment by ceckoslab** [comment]
Hello @korzol actually we have kind of "raw" beacons in table "beacons". I will handle this task from here.
